apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.kubetasker.io
spec:
  group: kubetasker.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Workflow
    plural: workflows
    shortNames:
    - wf
